services:

  wordpress:
    image: wordpress:latest
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=refactorian
      - WORDPRESS_DB_PASSWORD=refactorian
      - WORDPRESS_DB_NAME=refactorian
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content/
    ports:
      - 80:80

  db:
    image: mariadb:10.11
    #image: mysql:8.1
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=refactorian
      - MYSQL_USER=refactorian
      - MYSQL_PASSWORD=refactorian
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
        - 8080:8080
    depends_on:
      - db
